/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashRouteImport } from './routes/_dash'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as DashTemplatesRouteImport } from './routes/_dash.templates'
import { Route as DashSettingsRouteImport } from './routes/_dash.settings'
import { Route as DashDocumentsRouteImport } from './routes/_dash.documents'
import { Route as DashDashboardRouteImport } from './routes/_dash.dashboard'
import { Route as DashChatRouteImport } from './routes/_dash.chat'
import { Route as DashBusinessProfileRouteImport } from './routes/_dash.business-profile'
import { Route as DashAutomationsRouteImport } from './routes/_dash.automations'
import { Route as DashActivityRouteImport } from './routes/_dash.activity'
import { Route as DashAutomationsIndexRouteImport } from './routes/_dash.automations.index'
import { Route as DashAutomationsNewRouteImport } from './routes/_dash.automations.new'
import { Route as DashAutomationsIdRouteImport } from './routes/_dash.automations.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashRoute = DashRouteImport.update({
  id: '/_dash',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashTemplatesRoute = DashTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => DashRoute,
} as any)
const DashSettingsRoute = DashSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashRoute,
} as any)
const DashDocumentsRoute = DashDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => DashRoute,
} as any)
const DashDashboardRoute = DashDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashRoute,
} as any)
const DashChatRoute = DashChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => DashRoute,
} as any)
const DashBusinessProfileRoute = DashBusinessProfileRouteImport.update({
  id: '/business-profile',
  path: '/business-profile',
  getParentRoute: () => DashRoute,
} as any)
const DashAutomationsRoute = DashAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => DashRoute,
} as any)
const DashActivityRoute = DashActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => DashRoute,
} as any)
const DashAutomationsIndexRoute = DashAutomationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashAutomationsRoute,
} as any)
const DashAutomationsNewRoute = DashAutomationsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashAutomationsRoute,
} as any)
const DashAutomationsIdRoute = DashAutomationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashAutomationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/activity': typeof DashActivityRoute
  '/automations': typeof DashAutomationsRouteWithChildren
  '/business-profile': typeof DashBusinessProfileRoute
  '/chat': typeof DashChatRoute
  '/dashboard': typeof DashDashboardRoute
  '/documents': typeof DashDocumentsRoute
  '/settings': typeof DashSettingsRoute
  '/templates': typeof DashTemplatesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/automations/$id': typeof DashAutomationsIdRoute
  '/automations/new': typeof DashAutomationsNewRoute
  '/automations/': typeof DashAutomationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/activity': typeof DashActivityRoute
  '/business-profile': typeof DashBusinessProfileRoute
  '/chat': typeof DashChatRoute
  '/dashboard': typeof DashDashboardRoute
  '/documents': typeof DashDocumentsRoute
  '/settings': typeof DashSettingsRoute
  '/templates': typeof DashTemplatesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/automations/$id': typeof DashAutomationsIdRoute
  '/automations/new': typeof DashAutomationsNewRoute
  '/automations': typeof DashAutomationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dash': typeof DashRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_dash/activity': typeof DashActivityRoute
  '/_dash/automations': typeof DashAutomationsRouteWithChildren
  '/_dash/business-profile': typeof DashBusinessProfileRoute
  '/_dash/chat': typeof DashChatRoute
  '/_dash/dashboard': typeof DashDashboardRoute
  '/_dash/documents': typeof DashDocumentsRoute
  '/_dash/settings': typeof DashSettingsRoute
  '/_dash/templates': typeof DashTemplatesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/_dash/automations/$id': typeof DashAutomationsIdRoute
  '/_dash/automations/new': typeof DashAutomationsNewRoute
  '/_dash/automations/': typeof DashAutomationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/activity'
    | '/automations'
    | '/business-profile'
    | '/chat'
    | '/dashboard'
    | '/documents'
    | '/settings'
    | '/templates'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/automations/$id'
    | '/automations/new'
    | '/automations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/activity'
    | '/business-profile'
    | '/chat'
    | '/dashboard'
    | '/documents'
    | '/settings'
    | '/templates'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/automations/$id'
    | '/automations/new'
    | '/automations'
  id:
    | '__root__'
    | '/'
    | '/_dash'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/_dash/activity'
    | '/_dash/automations'
    | '/_dash/business-profile'
    | '/_dash/chat'
    | '/_dash/dashboard'
    | '/_dash/documents'
    | '/_dash/settings'
    | '/_dash/templates'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/_dash/automations/$id'
    | '/_dash/automations/new'
    | '/_dash/automations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashRoute: typeof DashRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash': {
      id: '/_dash'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash/templates': {
      id: '/_dash/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof DashTemplatesRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/settings': {
      id: '/_dash/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashSettingsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/documents': {
      id: '/_dash/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DashDocumentsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/dashboard': {
      id: '/_dash/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashDashboardRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/chat': {
      id: '/_dash/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof DashChatRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/business-profile': {
      id: '/_dash/business-profile'
      path: '/business-profile'
      fullPath: '/business-profile'
      preLoaderRoute: typeof DashBusinessProfileRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/automations': {
      id: '/_dash/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof DashAutomationsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/activity': {
      id: '/_dash/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof DashActivityRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/automations/': {
      id: '/_dash/automations/'
      path: '/'
      fullPath: '/automations/'
      preLoaderRoute: typeof DashAutomationsIndexRouteImport
      parentRoute: typeof DashAutomationsRoute
    }
    '/_dash/automations/new': {
      id: '/_dash/automations/new'
      path: '/new'
      fullPath: '/automations/new'
      preLoaderRoute: typeof DashAutomationsNewRouteImport
      parentRoute: typeof DashAutomationsRoute
    }
    '/_dash/automations/$id': {
      id: '/_dash/automations/$id'
      path: '/$id'
      fullPath: '/automations/$id'
      preLoaderRoute: typeof DashAutomationsIdRouteImport
      parentRoute: typeof DashAutomationsRoute
    }
  }
}

interface DashAutomationsRouteChildren {
  DashAutomationsIdRoute: typeof DashAutomationsIdRoute
  DashAutomationsNewRoute: typeof DashAutomationsNewRoute
  DashAutomationsIndexRoute: typeof DashAutomationsIndexRoute
}

const DashAutomationsRouteChildren: DashAutomationsRouteChildren = {
  DashAutomationsIdRoute: DashAutomationsIdRoute,
  DashAutomationsNewRoute: DashAutomationsNewRoute,
  DashAutomationsIndexRoute: DashAutomationsIndexRoute,
}

const DashAutomationsRouteWithChildren = DashAutomationsRoute._addFileChildren(
  DashAutomationsRouteChildren,
)

interface DashRouteChildren {
  DashActivityRoute: typeof DashActivityRoute
  DashAutomationsRoute: typeof DashAutomationsRouteWithChildren
  DashBusinessProfileRoute: typeof DashBusinessProfileRoute
  DashChatRoute: typeof DashChatRoute
  DashDashboardRoute: typeof DashDashboardRoute
  DashDocumentsRoute: typeof DashDocumentsRoute
  DashSettingsRoute: typeof DashSettingsRoute
  DashTemplatesRoute: typeof DashTemplatesRoute
}

const DashRouteChildren: DashRouteChildren = {
  DashActivityRoute: DashActivityRoute,
  DashAutomationsRoute: DashAutomationsRouteWithChildren,
  DashBusinessProfileRoute: DashBusinessProfileRoute,
  DashChatRoute: DashChatRoute,
  DashDashboardRoute: DashDashboardRoute,
  DashDocumentsRoute: DashDocumentsRoute,
  DashSettingsRoute: DashSettingsRoute,
  DashTemplatesRoute: DashTemplatesRoute,
}

const DashRouteWithChildren = DashRoute._addFileChildren(DashRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashRoute: DashRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
